services:
  airflow-db:
    image: postgres:15
    container_name: finascore-airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  airflow-init:
    build:
      context: .
      dockerfile: dockerfile.airflow
    image: custom-airflow:latest  
    container_name: finascore-airflow-init
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname FinaScore
      --lastname Admin
      --role Admin
      --email admin@finascore.local
      "

  airflow-webserver:
    image: custom-airflow:latest
    build:
      context: .
      dockerfile: dockerfile.airflow
    container_name: finascore-airflow-webserver
    depends_on:
      - airflow-db
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/project
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    ports:
      - "8080:8080"
    command: webserver
    restart: unless-stopped

  airflow-scheduler:
    image: custom-airflow:latest  
    build:
      context: .
      dockerfile: dockerfile.airflow
    container_name: finascore-airflow-scheduler
    depends_on:
      - airflow-db
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/project
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    command: scheduler
    restart: unless-stopped

volumes:
  airflow_db_data: